cc = gcc
# gcc .\index.c .\lib\link-create.c -o index
# $(cc) index.c .\lib\link-create.c .\lib\link_print.c -o index
main:	index.c
			gcc index.c -o index.exe
			./index.exe

basic: basic.c
			gcc basic.c -o index.exe
			./index.exe